version: '3.8'

services:
  web:
    image: alizaibdocker/ssis-app:latest
    container_name: ssis_web
    ports:
      - "80:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=AleySQLZayb029
      - DB_NAME=ssis
    depends_on:
      db:
        condition: service_healthy
    restart: always

  db:
    image: mysql:8.0
    container_name: ssis_db
    environment:
      - MYSQL_ROOT_PASSWORD=AleySQLZayb029
      - MYSQL_DATABASE=ssis
    volumes:
      - ssis_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pAleySQLZayb029"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  ssis_db_data:
